2021-11-22 23:00:23,256 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'post_body'
2021-11-22 23:01:07,461 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:03:18,355 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:03:21,363 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'post_body'
2021-11-22 23:04:57,216 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:05:41,471 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:05:42,207 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'post_body'
2021-11-22 23:06:05,661 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'post_body'
2021-11-22 23:06:32,866 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:11:16,474 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:11:39,561 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:11:45,244 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:12:24,334 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:12:27,163 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:12:34,703 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'post_body'
2021-11-22 23:12:42,132 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:12:43,464 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/danya/microblog/app/routes.py", line 292, in delete_post
    return render_template('delete_post.html', post = post, title='Delete Post', form = form ,post_body = post_body)
NameError: name 'post_body' is not defined
2021-11-22 23:13:02,171 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:13:58,444 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:14:17,287 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 23:14:52,378 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-23 01:14:22,093 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-23 01:14:23,087 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-23 01:17:32,198 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
