2021-11-22 03:11:29,686 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/lib/python3.9/smtplib.py", line 872, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.9/smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/lib/python3.9/smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/lib/python3.9/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.9/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 15, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/danya/microblog/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python3.9/smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.9/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python3.9/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/lib/python3.9/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2021-11-22 03:18:01,697 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 03:25:22,120 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 03:25:55,150 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 03:27:21,552 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 03:39:51,175 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 03:52:31,827 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 03:57:08,804 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:04:33,560 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:06:31,829 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:10:47,644 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:10:48,234 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:11:43,447 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:14:26,451 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:14:27,034 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:30:16,078 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:32:49,799 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:33:41,428 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:38:28,609 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:39:40,111 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:40:42,906 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 04:41:49,374 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:40:58,350 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:41:00,212 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:43:10,058 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:43:10,606 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:47:27,664 ERROR: Exception on /user/myNone [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/danya/microblog/app/routes.py", line 184, in user
    return render_template('user.html', user = user, posts = posts.items, next_url = next_url, prev_url = prev_url)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "index.html" %}
  File "/home/danya/microblog/app/templates/index.html", line 41, in top-level template code
    {% block content %}
  File "/home/danya/microblog/app/templates/user.html", line 34, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-11-22 16:51:00,608 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:52:15,199 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:52:36,084 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:52:49,502 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:56:15,221 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:57:59,757 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 16:58:12,927 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
