2021-11-22 22:09:16,767 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'body'
2021-11-22 22:09:52,542 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:10:02,527 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:10:04,092 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'body'
2021-11-22 22:10:19,441 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:11:47,463 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:13:22,031 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:14:25,656 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:14:34,426 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:16:27,832 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'body'
2021-11-22 22:19:42,939 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:19:43,892 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: delete_post() missing 1 required positional argument: 'body'
2021-11-22 22:21:29,661 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:21:30,149 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/danya/microblog/app/routes.py", line 279, in delete_post
    post = Post.query.filter_by(body=form.body.data).first()
AttributeError: 'DeletePost' object has no attribute 'body'
2021-11-22 22:22:11,869 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:22:18,580 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:22:38,595 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:22:41,077 ERROR: Exception on /delete_post [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/danya/microblog/app/routes.py", line 289, in delete_post
    return render_template('delete_post.html', post = post, title='Delete Post', form = form)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/delete_post.html", line 9, in template
    {{ form.post.(size=140) }}
jinja2.exceptions.TemplateSyntaxError: expected name or number
2021-11-22 22:24:05,426 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:25:01,891 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:25:04,583 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:25:06,230 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:25:07,875 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:25:51,058 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:26:29,134 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
2021-11-22 22:26:49,150 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:54]
