2021-11-28 17:02:16,950 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:03:28,645 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:06:30,453 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:08:14,854 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:10:08,627 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:12:54,401 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:12:56,640 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:13:02,207 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:13:21,458 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:16:32,259 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:16:48,528 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:17:49,657 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:17:54,134 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:22:37,129 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:37:12,887 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:37:13,991 ERROR: Exception on / [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/danya/microblog/app/routes.py", line 67, in index
    return render_template('index.html', form = form, posts = posts.items, next_url = next_url, prev_url = prev_url, title='General')
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/index.html", line 20, in top-level template code
    $(destElem).html('<img src="{{ url_for(static , filename= loading.gif) }}">');
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'loading' is undefined
2021-11-28 17:39:49,665 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:40:35,174 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:42:38,375 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:45:13,483 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:45:53,822 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:47:33,211 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:48:08,802 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:48:40,969 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:49:13,030 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:49:31,174 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:49:56,873 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 17:53:57,854 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 18:16:17,030 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 18:16:19,596 ERROR: Exception on /explore [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/danya/microblog/app/routes.py", line 288, in explore
    return render_template('index.html', posts=posts.items, next_url = next_url, prev_url = prev_url, title='Explore')
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/base.html
2021-11-28 18:18:05,236 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 18:18:07,359 ERROR: Exception on /explore [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/danya/microblog/app/routes.py", line 288, in explore
    return render_template('index.html', posts=posts.items, next_url = next_url, prev_url = prev_url, title='Explore')
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends 'bootstrap/index.html' %}
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/index.html
2021-11-28 18:20:39,963 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-28 18:20:41,670 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
